### ISSUE TITLE
Season 4 possible?

### ISSUE THREAD

**Issue by Puuhapete1** [MonsterMannen/DiscordBotNodeJs#1]
Everything looks good, but how could I change season 3 stats to season 4?

Thank you!

**Comment by MonsterMannen** [comment]
What do you mean?
The bot got 2 fortnite commands:
`.f7` which gives stats from the last 7 days and
`.f` which gives lifetime stats
neither of these are season dependent.

**Comment by Puuhapete1** [comment]
Sorry wrong bot
