### ISSUE TITLE
Music end problem.

### ISSUE THREAD

**Issue by mondoc446** [MonsterMannen/DiscordBotNodeJs#6]
Hi. I wanted to partially use the music part of the bot. I copied everything and adapted everything but always I get the same problem. The bot enters and leaves as soon as it joins. But why?

**Comment by MonsterMannen** [comment]
Hoho

The bot enters and leaves a voice channel or you mean it leaves your server?

You got the .env file with a bot token and a youtube api key?

Do you not get any console output errors? 
Maybe you need FFmpeg installed and in path?
@supermanYT

**Comment by MonsterMannen** [comment]
Go check #7 might be the same problem
